/* prc_parameters.h.  Generated automatically by makepanda.py */
#undef DEFAULT_PRC_DIR
#define PRC_DCONFIG_TRUST_LEVEL 0
#undef PRC_DIR_ENVVARS
#undef PRC_ENCRYPTED_PATTERNS
#define PRC_ENCRYPTION_KEY ""
#define PRC_EXECUTABLE_ARGS_ENVVAR "PANDA_PRC_XARGS"
#undef PRC_EXECUTABLE_PATTERNS
#define PRC_INC_TRUST_LEVEL 0
#undef PRC_PATH2_ENVVARS
#undef PRC_PATH_ENVVARS
#undef PRC_PATTERNS
#define PRC_PUBLIC_KEYS_FILENAME ""
#undef PRC_RESPECT_TRUST_LEVEL
